spring:
   datasource:
    password: 123456
    username: root
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3307/fornecedor?useTimezone=true&serverTimezone=UTC'
  jpa:
    hibernate:
      ddl-auto: update
